# Kanagawa - Kitty Terminal Colors

# The basic colors
foreground              #C8C093
background              #16161D
selection_foreground    #16161D
selection_background    #C8C093

# Cursor colors
cursor                  #C8C093
cursor_text_color       #16161D

# URL underline color when hovering with mouse
url_color               #C8C093

# Tab bar colors
active_tab_foreground   #16161D
active_tab_background   #7E9CD8
inactive_tab_foreground #C8C093
inactive_tab_background #1F1F28
tab_bar_background      #16161D

# Colors for marks (marked text in the terminal)
mark1_foreground #16161D
mark1_background #7E9CD8
mark2_foreground #16161D
mark2_background #957FB8
mark3_foreground #16161D
mark3_background #6A9589

# The 16 terminal colors

# black
color0 #16161D
color8 #727169

# red
color1 #C34043
color9 #E82424

# green
color2 #76946A
color10 #98BB6C

# yellow
color3 #C0A36E
color11 #E6C384

# blue
color4 #7E9CD8
color12 #7FB4CA

# magenta
color5 #957FB8
color13 #938AA9

# cyan
color6 #6A9589
color14 #7AA89F

# white
color7 #C8C093
color15 #DCD7BA
