# One Dark - Hyprland Appearance

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(97,175,239) rgba(198,120,221) 45deg
    col.inactive_border = rgba(92,99,112) rgba(40,44,52) 45deg
    layout = dwindle
    allow_tearing = false
}

decoration {
    rounding = 10
    
    blur {
        enabled = true
        size = 3
        passes = 1
        vibrancy = 0.1696
        vibrancy_darkness = 0.6
        noise = 0.02
        contrast = 1.3
        brightness = 0.8
    }
    
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
        offset = 0, 2
    }
}

animations {
    enabled = true
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 6, wind, slide
    animation = windowsOut, 1, 6, winOut, slide
    animation = windowsMove, 1, 6, wind
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, winIn
    animation = workspaces, 1, 6, default, slidevert
}
